# Generated by Django 3.2.16 on 2023-02-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fun_activities',
            field=models.TextField(blank=True),
        ),
    ]
