# Generated by Django 3.2.16 on 2023-02-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_fun_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
