# Generated by Django 3.2.16 on 2023-02-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='intro1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='intro2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='intro3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='intro4',
            field=models.CharField(max_length=20),
        ),
    ]
